-- Paper trading account (single row)
CREATE TABLE IF NOT EXISTS paper_account (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    balance REAL NOT NULL DEFAULT 10000.00,
    starting_balance REAL NOT NULL DEFAULT 10000.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO paper_account (id, balance, starting_balance) VALUES (1, 10000.00, 10000.00);

-- Paper positions
CREATE TABLE IF NOT EXISTS paper_positions (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    ticker TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('yes', 'no')),
    contracts INTEGER NOT NULL CHECK (contracts > 0),
    avg_price REAL NOT NULL,
    total_cost REAL NOT NULL,
    total_fees REAL NOT NULL,
    settlement_time TIMESTAMP NOT NULL,
    settled INTEGER NOT NULL DEFAULT 0,
    settled_at TIMESTAMP,
    settlement_value REAL,
    realized_pnl REAL,
    trade_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_positions_settled ON paper_positions(settled);
CREATE INDEX IF NOT EXISTS idx_positions_trade ON paper_positions(trade_id);

-- Paper trades (groups of positions from one arbitrage execution)
CREATE TABLE IF NOT EXISTS paper_trades (
    id TEXT PRIMARY KEY,
    executed_at TIMESTAMP NOT NULL,
    asset TEXT NOT NULL,
    total_cost REAL NOT NULL,
    total_fees REAL NOT NULL,
    contracts_per_leg INTEGER NOT NULL,
    expected_payout REAL NOT NULL,
    expected_profit REAL NOT NULL,
    expected_profit_pct REAL NOT NULL,
    actual_payout REAL,
    actual_profit REAL,
    legs_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'settled', 'partial'))
);

CREATE INDEX IF NOT EXISTS idx_trades_status ON paper_trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_date ON paper_trades(executed_at);

-- Opportunity history (for analytics)
CREATE TABLE IF NOT EXISTS opportunity_history (
    id TEXT PRIMARY KEY,
    detected_at TIMESTAMP NOT NULL,
    asset TEXT NOT NULL,
    settlement_time TIMESTAMP NOT NULL,
    threshold_ticker TEXT NOT NULL,
    threshold_strike REAL NOT NULL,
    threshold_yes_price REAL NOT NULL,
    implied_price REAL NOT NULL,
    divergence REAL NOT NULL,
    net_profit_pct REAL NOT NULL,
    max_liquidity_usd REAL NOT NULL,
    bracket_count INTEGER NOT NULL,
    was_traded INTEGER NOT NULL DEFAULT 0,
    trade_id TEXT,
    trade_mode TEXT CHECK (trade_mode IS NULL OR trade_mode IN ('paper', 'live'))
);

CREATE INDEX IF NOT EXISTS idx_opp_date ON opportunity_history(detected_at);

-- Manual orders (both paper and live mode)
CREATE TABLE IF NOT EXISTS manual_orders (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ticker TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('yes', 'no')),
    action TEXT NOT NULL CHECK (action IN ('buy', 'sell')),
    count INTEGER NOT NULL CHECK (count > 0),
    price_cents INTEGER NOT NULL CHECK (price_cents >= 1 AND price_cents <= 99),
    mode TEXT NOT NULL CHECK (mode IN ('paper', 'live')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'filled', 'partial', 'cancelled', 'failed')),
    filled_count INTEGER DEFAULT 0,
    avg_fill_price REAL,
    total_cost REAL,
    total_fees REAL,
    kalshi_order_id TEXT,
    error TEXT,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_mode ON manual_orders(mode);
CREATE INDEX IF NOT EXISTS idx_orders_status ON manual_orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON manual_orders(created_at);

-- Watchlist (saved markets for quick access)
CREATE TABLE IF NOT EXISTS watchlist (
    id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    subtitle TEXT,
    notes TEXT,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_watchlist_ticker ON watchlist(ticker);
CREATE INDEX IF NOT EXISTS idx_watchlist_added ON watchlist(added_at);

-- ==============================================
-- AUTO-TRADER TABLES
-- ==============================================

-- Trading signals generated by edge detection
CREATE TABLE IF NOT EXISTS trading_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    signal_type TEXT NOT NULL,  -- 'buy_yes', 'buy_no', 'sell_yes', 'sell_no'
    edge_percent REAL NOT NULL,  -- e.g., 15.5 means 15.5% edge
    model_prob REAL NOT NULL,    -- model's probability estimate
    market_price INTEGER NOT NULL,  -- current market price in cents
    recommended_size INTEGER NOT NULL,  -- suggested position size
    source TEXT NOT NULL,  -- 'btc_price', 'weather_nws', 'manual', etc.
    status TEXT DEFAULT 'pending',  -- 'pending', 'executed', 'expired', 'rejected'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    executed_at TIMESTAMP,
    execution_price INTEGER,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_signals_status ON trading_signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_created ON trading_signals(created_at);
CREATE INDEX IF NOT EXISTS idx_signals_ticker ON trading_signals(ticker);

-- Auto-trader configuration
CREATE TABLE IF NOT EXISTS auto_trader_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),  -- Single row table
    enabled INTEGER DEFAULT 0,  -- 0=off, 1=paper only, 2=live enabled
    min_edge_percent REAL DEFAULT 10.0,  -- minimum edge to trade
    max_position_size INTEGER DEFAULT 100,  -- max contracts per market
    max_daily_loss_cents INTEGER DEFAULT 10000,  -- $100 max daily loss
    max_open_positions INTEGER DEFAULT 10,
    allowed_series TEXT DEFAULT 'KXBTC,KXBTCD',  -- comma-separated series tickers
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default config
INSERT OR IGNORE INTO auto_trader_config (id, enabled, min_edge_percent, max_position_size, max_daily_loss_cents, max_open_positions, allowed_series)
VALUES (1, 0, 10.0, 100, 10000, 10, 'KXBTC,KXBTCD');

-- Track daily P&L for risk management
CREATE TABLE IF NOT EXISTS daily_pnl (
    date TEXT PRIMARY KEY,  -- YYYY-MM-DD
    realized_pnl_cents INTEGER DEFAULT 0,
    trades_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_pnl_date ON daily_pnl(date);

-- ===========================================
-- BTC ARBITRAGE TABLES
-- ===========================================

-- BTC Arbitrage executions
CREATE TABLE IF NOT EXISTS btc_arb_executions (
    id TEXT PRIMARY KEY,
    opportunity_id TEXT NOT NULL,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mode TEXT NOT NULL,  -- 'paper' or 'live'
    contracts_per_leg INTEGER NOT NULL,
    total_cost_cents INTEGER NOT NULL,
    total_fees_cents INTEGER NOT NULL,
    guaranteed_profit_cents INTEGER NOT NULL,
    status TEXT DEFAULT 'open',  -- 'open', 'settled', 'partial'
    kalshi_response TEXT,
    settled_at TIMESTAMP,
    settlement_outcome TEXT,
    actual_payout_cents INTEGER,
    actual_profit_cents INTEGER
);

-- BTC Arbitrage scanner configuration
CREATE TABLE IF NOT EXISTS btc_arb_config (
    id INTEGER PRIMARY KEY DEFAULT 1,
    min_edge_percent REAL DEFAULT 3.0,
    default_budget_cents INTEGER DEFAULT 10000,
    auto_trade_enabled INTEGER DEFAULT 0,
    scan_interval_seconds REAL DEFAULT 2.0,
    max_position_per_opp_cents INTEGER DEFAULT 50000,
    mode TEXT DEFAULT 'paper',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO btc_arb_config (id) VALUES (1);

-- ===========================================
-- CORE TRADING INFRASTRUCTURE TABLES
-- ===========================================

-- Unified signals table (v2) for all strategies
CREATE TABLE IF NOT EXISTS signals_v2 (
    id TEXT PRIMARY KEY,
    strategy_type TEXT NOT NULL,  -- 'weather', 'btc', 'economic'
    ticker TEXT NOT NULL,
    signal_type TEXT NOT NULL,  -- 'directional', 'arbitrage', 'spread'
    edge_percent REAL NOT NULL,
    model_prob REAL NOT NULL,
    market_price INTEGER NOT NULL,
    recommended_size INTEGER NOT NULL,
    confidence REAL DEFAULT 1.0,
    is_arbitrage INTEGER DEFAULT 0,
    legs_json TEXT,  -- JSON array of leg objects
    metadata_json TEXT,  -- Additional strategy-specific data
    status TEXT DEFAULT 'pending',  -- 'pending', 'executing', 'executed', 'rejected', 'expired', 'failed'
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    executed_at TIMESTAMP,
    execution_price INTEGER,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_signals_v2_status ON signals_v2(status);
CREATE INDEX IF NOT EXISTS idx_signals_v2_strategy ON signals_v2(strategy_type);
CREATE INDEX IF NOT EXISTS idx_signals_v2_ticker ON signals_v2(ticker);
CREATE INDEX IF NOT EXISTS idx_signals_v2_created ON signals_v2(created_at);
CREATE INDEX IF NOT EXISTS idx_signals_v2_expires ON signals_v2(expires_at);

-- Trade records for performance tracking
CREATE TABLE IF NOT EXISTS trade_records (
    id TEXT PRIMARY KEY,
    strategy_type TEXT NOT NULL,
    ticker TEXT NOT NULL,
    side TEXT NOT NULL,  -- 'yes' or 'no'
    contracts INTEGER NOT NULL,
    entry_price INTEGER NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    exit_price INTEGER,
    exit_time TIMESTAMP,
    fees_cents INTEGER DEFAULT 0,
    pnl_cents INTEGER,
    status TEXT DEFAULT 'open',  -- 'open', 'closed', 'settled'
    is_arbitrage INTEGER DEFAULT 0,
    batch_id TEXT,
    signal_id TEXT,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trade_records(strategy_type);
CREATE INDEX IF NOT EXISTS idx_trades_status_v2 ON trade_records(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trade_records(entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_batch ON trade_records(batch_id);

-- Orchestrator configuration (single row)
CREATE TABLE IF NOT EXISTS orchestrator_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    auto_trade_enabled INTEGER DEFAULT 0,
    mode TEXT DEFAULT 'paper',  -- 'paper' or 'live'
    kelly_fraction REAL DEFAULT 0.25,
    min_edge_percent REAL DEFAULT 5.0,
    max_position_per_market INTEGER DEFAULT 100,
    max_daily_loss_cents INTEGER DEFAULT 5000,
    cb_max_consecutive_losses INTEGER DEFAULT 5,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO orchestrator_config (id) VALUES (1);

-- Circuit breaker state
CREATE TABLE IF NOT EXISTS circuit_breaker_state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    is_tripped INTEGER DEFAULT 0,
    trip_reason TEXT,
    tripped_at TIMESTAMP,
    consecutive_losses INTEGER DEFAULT 0,
    daily_loss_cents INTEGER DEFAULT 0,
    hourly_losses INTEGER DEFAULT 0,
    last_reset TIMESTAMP,
    last_trade_time TIMESTAMP
);

INSERT OR IGNORE INTO circuit_breaker_state (id, is_tripped, consecutive_losses, daily_loss_cents, hourly_losses)
VALUES (1, 0, 0, 0, 0);

-- Risk manager positions (live tracking)
CREATE TABLE IF NOT EXISTS risk_positions (
    ticker TEXT PRIMARY KEY,
    contracts INTEGER NOT NULL,
    avg_price INTEGER NOT NULL,
    side TEXT NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_risk_positions_updated ON risk_positions(updated_at);

-- Daily P&L tracking for risk management (enhanced)
CREATE TABLE IF NOT EXISTS daily_pnl_v2 (
    date TEXT PRIMARY KEY,  -- YYYY-MM-DD
    realized_pnl_cents INTEGER DEFAULT 0,
    unrealized_pnl_cents INTEGER DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_fees_cents INTEGER DEFAULT 0,
    max_drawdown_cents INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_pnl_v2_date ON daily_pnl_v2(date);

-- Historical opportunities for backtesting
CREATE TABLE IF NOT EXISTS historical_opportunities (
    id TEXT PRIMARY KEY,
    strategy_type TEXT NOT NULL,
    ticker TEXT NOT NULL,
    signal_type TEXT NOT NULL,
    edge_percent REAL NOT NULL,
    model_prob REAL NOT NULL,
    market_price INTEGER NOT NULL,
    recommended_size INTEGER DEFAULT 10,
    is_arbitrage INTEGER DEFAULT 0,
    timestamp TIMESTAMP NOT NULL,
    resolution_time TIMESTAMP,
    outcome TEXT,  -- 'won', 'lost', 'expired'
    won INTEGER,
    metadata_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_hist_opp_strategy ON historical_opportunities(strategy_type);
CREATE INDEX IF NOT EXISTS idx_hist_opp_timestamp ON historical_opportunities(timestamp);
CREATE INDEX IF NOT EXISTS idx_hist_opp_outcome ON historical_opportunities(outcome);

-- Alert history
CREATE TABLE IF NOT EXISTS alert_history (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    priority TEXT NOT NULL,
    data_json TEXT,
    created_at TIMESTAMP NOT NULL,
    acknowledged INTEGER DEFAULT 0,
    acknowledged_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alerts_created ON alert_history(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON alert_history(type);
CREATE INDEX IF NOT EXISTS idx_alerts_ack ON alert_history(acknowledged);
