-- Paper trading account (single row)
CREATE TABLE IF NOT EXISTS paper_account (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    balance REAL NOT NULL DEFAULT 10000.00,
    starting_balance REAL NOT NULL DEFAULT 10000.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO paper_account (id, balance, starting_balance) VALUES (1, 10000.00, 10000.00);

-- Paper positions
CREATE TABLE IF NOT EXISTS paper_positions (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    ticker TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('yes', 'no')),
    contracts INTEGER NOT NULL CHECK (contracts > 0),
    avg_price REAL NOT NULL,
    total_cost REAL NOT NULL,
    total_fees REAL NOT NULL,
    settlement_time TIMESTAMP NOT NULL,
    settled INTEGER NOT NULL DEFAULT 0,
    settled_at TIMESTAMP,
    settlement_value REAL,
    realized_pnl REAL,
    trade_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_positions_settled ON paper_positions(settled);
CREATE INDEX IF NOT EXISTS idx_positions_trade ON paper_positions(trade_id);

-- Paper trades (groups of positions from one arbitrage execution)
CREATE TABLE IF NOT EXISTS paper_trades (
    id TEXT PRIMARY KEY,
    executed_at TIMESTAMP NOT NULL,
    asset TEXT NOT NULL,
    total_cost REAL NOT NULL,
    total_fees REAL NOT NULL,
    contracts_per_leg INTEGER NOT NULL,
    expected_payout REAL NOT NULL,
    expected_profit REAL NOT NULL,
    expected_profit_pct REAL NOT NULL,
    actual_payout REAL,
    actual_profit REAL,
    legs_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'settled', 'partial'))
);

CREATE INDEX IF NOT EXISTS idx_trades_status ON paper_trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_date ON paper_trades(executed_at);

-- Opportunity history (for analytics)
CREATE TABLE IF NOT EXISTS opportunity_history (
    id TEXT PRIMARY KEY,
    detected_at TIMESTAMP NOT NULL,
    asset TEXT NOT NULL,
    settlement_time TIMESTAMP NOT NULL,
    threshold_ticker TEXT NOT NULL,
    threshold_strike REAL NOT NULL,
    threshold_yes_price REAL NOT NULL,
    implied_price REAL NOT NULL,
    divergence REAL NOT NULL,
    net_profit_pct REAL NOT NULL,
    max_liquidity_usd REAL NOT NULL,
    bracket_count INTEGER NOT NULL,
    was_traded INTEGER NOT NULL DEFAULT 0,
    trade_id TEXT,
    trade_mode TEXT CHECK (trade_mode IS NULL OR trade_mode IN ('paper', 'live'))
);

CREATE INDEX IF NOT EXISTS idx_opp_date ON opportunity_history(detected_at);

-- Manual orders (both paper and live mode)
CREATE TABLE IF NOT EXISTS manual_orders (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ticker TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('yes', 'no')),
    action TEXT NOT NULL CHECK (action IN ('buy', 'sell')),
    count INTEGER NOT NULL CHECK (count > 0),
    price_cents INTEGER NOT NULL CHECK (price_cents >= 1 AND price_cents <= 99),
    mode TEXT NOT NULL CHECK (mode IN ('paper', 'live')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'filled', 'partial', 'cancelled', 'failed')),
    filled_count INTEGER DEFAULT 0,
    avg_fill_price REAL,
    total_cost REAL,
    total_fees REAL,
    kalshi_order_id TEXT,
    error TEXT,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_mode ON manual_orders(mode);
CREATE INDEX IF NOT EXISTS idx_orders_status ON manual_orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON manual_orders(created_at);

-- Watchlist (saved markets for quick access)
CREATE TABLE IF NOT EXISTS watchlist (
    id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    subtitle TEXT,
    notes TEXT,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_watchlist_ticker ON watchlist(ticker);
CREATE INDEX IF NOT EXISTS idx_watchlist_added ON watchlist(added_at);

-- ==============================================
-- AUTO-TRADER TABLES
-- ==============================================

-- Trading signals generated by edge detection
CREATE TABLE IF NOT EXISTS trading_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    signal_type TEXT NOT NULL,  -- 'buy_yes', 'buy_no', 'sell_yes', 'sell_no'
    edge_percent REAL NOT NULL,  -- e.g., 15.5 means 15.5% edge
    model_prob REAL NOT NULL,    -- model's probability estimate
    market_price INTEGER NOT NULL,  -- current market price in cents
    recommended_size INTEGER NOT NULL,  -- suggested position size
    source TEXT NOT NULL,  -- 'btc_price', 'weather_nws', 'manual', etc.
    status TEXT DEFAULT 'pending',  -- 'pending', 'executed', 'expired', 'rejected'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    executed_at TIMESTAMP,
    execution_price INTEGER,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_signals_status ON trading_signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_created ON trading_signals(created_at);
CREATE INDEX IF NOT EXISTS idx_signals_ticker ON trading_signals(ticker);

-- Auto-trader configuration
CREATE TABLE IF NOT EXISTS auto_trader_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),  -- Single row table
    enabled INTEGER DEFAULT 0,  -- 0=off, 1=paper only, 2=live enabled
    min_edge_percent REAL DEFAULT 10.0,  -- minimum edge to trade
    max_position_size INTEGER DEFAULT 100,  -- max contracts per market
    max_daily_loss_cents INTEGER DEFAULT 10000,  -- $100 max daily loss
    max_open_positions INTEGER DEFAULT 10,
    allowed_series TEXT DEFAULT 'KXBTC,KXBTCD',  -- comma-separated series tickers
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default config
INSERT OR IGNORE INTO auto_trader_config (id, enabled, min_edge_percent, max_position_size, max_daily_loss_cents, max_open_positions, allowed_series)
VALUES (1, 0, 10.0, 100, 10000, 10, 'KXBTC,KXBTCD');

-- Track daily P&L for risk management
CREATE TABLE IF NOT EXISTS daily_pnl (
    date TEXT PRIMARY KEY,  -- YYYY-MM-DD
    realized_pnl_cents INTEGER DEFAULT 0,
    trades_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_pnl_date ON daily_pnl(date);
